name: renew_right
description: "An app to manage insurance renewals for your customers."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase Dependencies
  firebase_core: ^3.4.0
  cloud_firestore: ^5.2.0
  firebase_auth: ^5.2.0

  # Utility Packages
  intl: ^0.19.0
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  path_provider: ^2.1.3
  share_plus: ^9.0.0
  gal: ^2.2.0
  
  # UI Package
  cupertino_icons: ^1.0.8
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: "^2.4.0"

flutter:
  uses-material-design: true

  # Declare the assets folder so your logo can be used
  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo1.png"
  min_sdk_android: 23

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo.png
  
  # Handle dark mode
  color_dark: "#FFFFFF"
  image_dark: assets/logo.png

  # Handle Android 12+
  android_12:
    image: assets/logo.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/logo.png
    icon_background_color_dark: "#FFFFFF"