// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz4upz2KzowBUHSlUFFfcehFVogjtbkRo',
    appId: '1:685682193957:web:32bf7dd53798bbf7c871cc',
    messagingSenderId: '685682193957',
    projectId: 'insurancemanager01',
    authDomain: 'insurancemanager01.firebaseapp.com',
    storageBucket: 'insurancemanager01.firebasestorage.app',
    measurementId: 'G-PHP0BZ5G2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkynvN0k05kL6g8sTZETkZ204NJq8q6hg',
    appId: '1:685682193957:android:3c675e0deed1dd8dc871cc',
    messagingSenderId: '685682193957',
    projectId: 'insurancemanager01',
    storageBucket: 'insurancemanager01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqKNJSVucEhiZ4Axc7unslq686hZY-hRA',
    appId: '1:685682193957:ios:dc07c1d420032e70c871cc',
    messagingSenderId: '685682193957',
    projectId: 'insurancemanager01',
    storageBucket: 'insurancemanager01.firebasestorage.app',
    iosBundleId: 'com.example.cscInsuranceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqKNJSVucEhiZ4Axc7unslq686hZY-hRA',
    appId: '1:685682193957:ios:dc07c1d420032e70c871cc',
    messagingSenderId: '685682193957',
    projectId: 'insurancemanager01',
    storageBucket: 'insurancemanager01.firebasestorage.app',
    iosBundleId: 'com.example.cscInsuranceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz4upz2KzowBUHSlUFFfcehFVogjtbkRo',
    appId: '1:685682193957:web:681944991a27ba1ec871cc',
    messagingSenderId: '685682193957',
    projectId: 'insurancemanager01',
    authDomain: 'insurancemanager01.firebaseapp.com',
    storageBucket: 'insurancemanager01.firebasestorage.app',
    measurementId: 'G-E7T3MN4307',
  );
}
